### ISSUE TITLE
windows keyboard to osx mac - Danish / Dansk tastatur

### ISSUE THREAD

**Issue by martinandersen3d** [ysoftwareab/xkb-for-macos#1]
remap a Danish Windows keyboard to a mac keyboard:

Features: 
@  = alt+2
| = |
{ = alt + 7 
} = alt+0

1. Place the file in: /Users/_your_user_name_/Library/Keyboard Layouts/
2. go System preferences > keyboard > input sources > Add Danish1
3. check the "show input in input bar"
4. up in right corner of script click the danish flag, select Danish1
5. Done

Verify:
alt+2 should be "@"

[Danish1.zip](https://github.com/andreineculau/OSX-PC-keyboard-layouts/files/1856294/Danish1.zip)

**Comment by martinandersen3d** [comment]
![skaermbillede 2018-03-28 kl 16 48 58](https://user-images.githubusercontent.com/19984581/38036995-3ccfeb3e-32a8-11e8-90da-ad2a09db9bdf.png)


![skaermbillede 2018-03-28 kl 16 48 37](https://user-images.githubusercontent.com/19984581/38037014-44d95fd6-32a8-11e8-9432-a79a87e56c1e.png)

**Comment by andreineculau** [comment]
Late to say it, but thanks 🙏 I think the new version of this repo based on X11 solves this.
